### ISSUE TITLE
[Bug] Missing "claimed" daily mission after 12am

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#226]
**Describe the bug (Actual behavior)**
Got 3 claimed daily mission but they're missing after 12AM

Screenshots
![image](https://user-images.githubusercontent.com/109064722/178328574-9bb474d0-f8d3-4f55-8c4b-554e9a30fa99.png)

**Expected behavior**
3 Claimed daily mission exist or get new 3 daily missions

**To Reproduce**
1. Finish some daily mission
2. wait until time pass 12am
3. See error

**Comment by stuart-lucis** [comment]
Update: Claimed Missions not showing after finish and claim 3 daily missions and refresh page
![image](https://user-images.githubusercontent.com/109064722/178425488-ab95726f-e82e-468e-9296-edc55e558bed.png)

**Comment by longvuit18** [comment]
@luatnd  please assign to @winwin2211

**Comment by winwin2211** [comment]
resolved
