### ISSUE TITLE
[Bug] Click update and wait for a long time but nothing returns

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#227]
**Describe the bug (Actual behavior)**
Click update and wait for a long time but nothing returns

Screenshots
![image](https://user-images.githubusercontent.com/109064722/178329577-e4a6ddf8-cb61-43d6-85ed-4db428d297a7.png)

**Expected behavior**
Should update recent match

**To Reproduce**
1. Play a game
2. Click on 'update' btn as in screenshot
3. See error

**Comment by luatnd-lucis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/NyjsTauo/294-test)
