### ISSUE TITLE
[Bug] Click "Update" but not update "Daily Mission"

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#228]
**Describe the bug (Actual behavior)**
Click "Update" but not update "Daily Mission" even though the "daily mission" is finished

Screenshots
- You can paste your screenshots image right here.
- Or Can drag and drop image / video here

**Expected behavior**
That "Daily mission" should be updated as Finish and ready to claim

**To Reproduce**
1. Play a game
2. Click on 'update'
3. See error

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
fixed
