### ISSUE TITLE
[Bug] Can't claim daily mission 

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#229]
**Describe the bug (Actual behavior)**
Can't claim mission as in screenshot, maybe because of #226, or maybe can't claim the last "Finished Mission"

Screenshots
![image](https://user-images.githubusercontent.com/109064722/178330533-eaed45db-d92a-4ae5-aa3f-807c732bbd14.png)

**Expected behavior**
Should claim the last finished mission to show the reward after completing all daily mission in that day

**To Reproduce**
1. Play to finish all daily mission
2. Click on 'claim'
3. See error

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stuart-lucis** [comment]
![image](https://user-images.githubusercontent.com/109064722/178425096-cf0c5ed9-c18e-40e6-b172-c783cf23be61.png)

Finish all daily mission but can't claim

**Comment by luatnd** [comment]
@longvuit18 4 quests logo must be always shown with ticked/untick status

**Comment by winwin2211** [comment]
resolved
