### ISSUE TITLE
[Bug] First Time Connect Game CSGO: Not showing Daily Mission

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#231]
**Describe the bug (Actual behavior)**
First Time Connect Game CSGO: Not showing Daily Mission, gamer had to click "Update" button to show "Daily Mission"

Screenshots
![image](https://user-images.githubusercontent.com/109064722/178420071-e578d359-b8c4-4280-999f-53bcb5e7d226.png)

**Expected behavior**
Daily Mission has to be showed right after gamer connect their game account

**To Reproduce**
1. Login Lucis account
2. Connect Game for the 1st time
3. Go to "Dashboard"
4. See error in "Daily Mission"

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by longvuit18** [comment]
fixed
