### ISSUE TITLE
PlayCore Lucis - Can not connect to Games

### ISSUE THREAD

**Issue by Hwngbob** [lucis-network/tournament-app#237]
**Describe the bug (Actual behavior)**
Can not connect to League of Legends
Screenshots
![image](https://user-images.githubusercontent.com/109072717/178454134-b1d52ce9-1c83-4483-bc4b-3979fdf9ec40.png)

**Expected behavior**
Connect successfully

**To Reproduce**
1. Go to 'Sign In with Google Account'
2. Click on 'Connect Game'
3. See error

**Desktop (please complete the following information):**
 - Browser [Chrome, Opera]

**Smartphone (please complete the following information):**

**Additional context**
Summoner Name: Marko

**Comment by kyanh2000** [comment]
My summoner's name is "LMN bake" have the similiar issue. 
Hope you guys asap

**Comment by longvuit18** [comment]
fixed with PR https://github.com/lucis-network/tournament-app/pull/240

**Comment by longvuit18** [comment]
fixed with PR https://github.com/lucis-network/tournament-app/pull/240
