### ISSUE TITLE
[Bug] Lucis Mission not updating

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#238]
**Describe the bug (Actual behavior)**
Play 5 matches but Lucis Mission isn't updated

Screenshots
![image](https://user-images.githubusercontent.com/109064722/178463431-8cd955f8-d8c4-4c23-b6fe-bc1a5888f2c0.png)
![image](https://user-images.githubusercontent.com/109064722/178463516-26c5b679-d155-4ae0-9e17-9f84226c8bf5.png)

**Expected behavior**
Lucis Mission should be updated after every matches

**To Reproduce**
1. Go to 'Mission'
2. See error

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
fixed

**Comment by Vanntmay** [comment]
On the Dev version without errors, need to follow up more
