### ISSUE TITLE
PlayCore - Dashboard & Mission Reports

### ISSUE THREAD

**Issue by Hwngbob** [lucis-network/tournament-app#239]
**Describe the bug (Actual behavior)**
Bug 1: Connected Account but there is no mission on dashboard, no recent matches stats
Bug 2: Disconnect Account after Refresh page
Bug 3: Can't reconnect Account after 2nd bug
Screenshots
![image](https://user-images.githubusercontent.com/109072717/178467277-efa9c679-2a07-4bb9-9ebe-93d8c9335e72.png)

**Expected behavior**
Connect successfully to Dashboard and Mission

**To Reproduce**
1. Go to 'Sign-in with Google (hungnq@lucis.network)' -> Already Connected to Summoner Name (Marko)
2. Click on 'Dashboard' -> No mission and recent matches record, 
3. Click on 'Daily Mission Update' -> Not respond, 
4. Refresh Page -> Gaming Account disconnected -> Can not reconnect, have to log out and sign-in again and back to Step 1

**Desktop (please complete the following information):**
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
fixed

**Comment by Vanntmay** [comment]
Không bị trên Dev, cần theo dõi thêm
