### ISSUE TITLE
[Bug] Daily mission box has wrong behavior

### ISSUE THREAD

**Issue by luatnd** [lucis-network/tournament-app#241]
**Describe the bug (Actual behavior)**
1. Why the box is open in grey-out image?
2. The app fired 2 requests: query isClaimBox() => Redundant

Screenshots
<img width="693" alt="image" src="https://user-images.githubusercontent.com/1859127/178529578-49abd348-014d-44ad-baca-76082cb44a7b.png">

**Expected behavior**
- complete 4 quests then the box will open with a normal box image, not grey-ed out, that is the only entry point to claim.

**To Reproduce**
1. Go to the Dashboard screen

**Additional context**
ENV: alpha-p2e
account @AbcNguyenLuat

**Comment by longvuit18** [comment]
@luatnd please assign to @winwin2211

**Comment by winwin2211** [comment]
resolved
