### ISSUE TITLE
[Bug]Profile

### ISSUE THREAD

**Issue by hoapk** [lucis-network/tournament-app#242]
**Describe the bug (Actual behavior)**

Screenshots
- You can paste your screenshots image right here.
- Or Can drag and drop image / video here

**Expected behavior**

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[Bug]Profile: 
- Add avatar
- Verify phone number
- share user name
- Create bio
- Fix UI profile

**Comment by huyennp** [comment]
No clear
