### ISSUE TITLE
[Bug] 6 Daily Missions CSGO???

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#243]
**Describe the bug (Actual behavior)**
After update, refresh many times, 6 daily mission shows up

Screenshots
![image](https://user-images.githubusercontent.com/109064722/178548499-a4c7b104-9406-49ab-8b59-15a354e05510.png)

**Expected behavior**
only 4 daily mission

**To Reproduce**
1. Go to 'Dashboard'

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
fixed
