### ISSUE TITLE
[Bug] Can't claim Lucis Mission

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#244]
**Describe the bug (Actual behavior)**
Can't claim Lucis Mission

Screenshots
![image](https://user-images.githubusercontent.com/109064722/178549628-b59096d1-9fbe-41e9-acd2-9b1b0c83c51b.png)

**Expected behavior**
Should claim successfully

**To Reproduce**
1. Go to 'Mission'
2. Click on 'Claim'
3. See error

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
fixed
