### ISSUE TITLE
[Bug] show LOL daily missions on CSGO Daily Mission page

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#246]
**Describe the bug (Actual behavior)**
show LOL daily missions on CSGO Daily Mission page

Screenshots
![image](https://user-images.githubusercontent.com/109064722/178649585-730f7294-9afd-488b-9dfe-94998bcdfaad.png)

**Expected behavior**

**To Reproduce**
1. Go to 'Dashboard'
2. Switch between CSGO and LOL game for 4-5 times in fast speed
3. Scroll down to 'Daily Mission'

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
fixed
