### ISSUE TITLE
[Bug] PlayCore - Connect Game Bugs, Missing daily mission & Recent match

### ISSUE THREAD

**Issue by Hwngbob** [lucis-network/tournament-app#248]
**Describe the bug (Actual behavior)**
Trouble in Connect Game LoL

Screenshots

**Expected behavior**
Connect Game in one-click

**To Reproduce**
1. Go to 'Login with Google' (Master@lucis.network)
2. Click on 'Connect Game' and submit Summoner Name
3. See Issue 'Can't connect Game, pls contact Lucis'
4. Logout and Login again -> League of Legends Account connected
5. Still no daily missions, recent matches, 

**Desktop (please complete the following information):**
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by longvuit18** [comment]
fixed in commit https://github.com/lucis-network/tournament-app/commit/3d438abad7df80b815899dcd8e50fa6615d1b9cd
