### ISSUE TITLE
[Bug]PlayCore - Not record recent matches and missions

### ISSUE THREAD

**Issue by Hwngbob** [lucis-network/tournament-app#252]
**Describe the bug (Actual behavior)**
Not record recent matches and missions after playing

Screenshots
![image](https://user-images.githubusercontent.com/109072717/178694656-5975bb3d-d89c-4a4b-98f7-ef63cecc6a6a.png)

**Expected behavior**
Record recent matches and update mission

**To Reproduce**
1. Go to 'Dashboard'
2. Recent matches recored is 5 months ago (id Game: Marko)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kyanh2000** [comment]
ID: LMD Naruto 
i just got a recorded match previous day

**Comment by Hwngbob** [comment]
Not update New Daily Mission, all the missions are the same from 2 days ago

**Comment by winwin2211** [comment]
resolved
