### ISSUE TITLE
[Bug] Daily Mission reset and claimable after claim

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#260]
**Describe the bug (Actual behavior)**
A Daily Mission is already claimed, but when play new match, it reset and can reclaim that mission
In this sitiuation, "Play a match with K/R Ratio > 0.4" is reset and user can claim 

Screenshots
![image](https://user-images.githubusercontent.com/109064722/178993774-ed7444d7-c9bb-4f16-a690-04baf7c6a830.png)

**Expected behavior**
Daily Mission can only renew when that day end

**To Reproduce**
1. Finish a mission with type "Play a match with K/R Ratio > 0.4"
2. Claim that mission
3. Play another match that can't finish that mission

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
resolved
