### ISSUE TITLE
[Bug] Playcore - Not update Missions

### ISSUE THREAD

**Issue by Hwngbob** [lucis-network/tournament-app#262]
**Describe the bug (Actual behavior)**
The same missions from 3 days ago

Screenshots
![image](https://user-images.githubusercontent.com/109072717/179134921-55a9d4b9-e38c-47a9-929f-d03c52821a3d.png)
**Expected behavior**
Update new daily missions everyday

**To Reproduce**
1. Go to 'Login'
2. Click on 'Dashboard'
3. See error

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
resolved
