### ISSUE TITLE
[Bug] PlayCore - Lucis Mission not updating

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#263]
**Describe the bug (Actual behavior)**
PlayCore - Lucis Mission not updating after play some matches

Screenshots
![image](https://user-images.githubusercontent.com/109064722/179142269-a0b0ce2a-de7c-42ce-b562-62a5dfa7618e.png)

**Expected behavior**
Lucis Mission Should be updated after any matches

**To Reproduce**
1. Play a game
2. Click on 'Mission '
3. See error

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
resolved

**Comment by Vanntmay** [comment]
Không bị trên Dev, cần theo dõi thêm

**Comment by Vanntmay** [comment]
Duplicate issue #238
