### ISSUE TITLE
PlayCore - Lucis Points should be rebalanced

### ISSUE THREAD

**Issue by Hwngbob** [lucis-network/tournament-app#264]
**Is your feature request related to a problem? Please describe.**
I find the score distribution in Playcore LOL matches unbalanced. I played 2 matches and they got me about 150 Lucis Point, so on average If I played 4 matches is enough for the limit of lucis points in 1 day. So I won't be motivated to go to Lucis PlayCore to check Daily Missions and Claim Rewards.

**Describe the solution you'd like**
A more balanced scoring system that give players maximum 50 points per day so they have to complete the Daily Missions to get enough points. Or Raise the Score of Daily Missions to motivate players to join the missions.

**Describe alternatives you've considered**

**Additional context**

**Comment by huyennp** [comment]
@tanductan
