### ISSUE TITLE
[Bug] Error in the calculation of Lucis Point after match

### ISSUE THREAD

**Issue by Hwngbob** [lucis-network/tournament-app#265]
**Describe the bug (Actual behavior)**
Error in the calculation of Lucis Point after match. I played ARAM where there is no wards. But in the end of the match, I still got Lucis Point Score for Ward placed and destroyed.

Screenshots
![image](https://user-images.githubusercontent.com/109072717/179146580-b5afb020-2581-4714-b150-cee33042de27.png)

**Expected behavior**
Accurately record the achievements of the matches.

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
resolved
