### ISSUE TITLE
[Bug] Total Points in Recent Matches doesn't match in View All History

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#273]
**Describe the bug (Actual behavior)**
Recent Matches only shows 5 latest matches so maybe the Points Number isn't approximately calculated

Screenshots
![image](https://user-images.githubusercontent.com/109064722/179336886-da9d99dc-fb5d-4825-a4b8-c87be04c57f8.png)
![image](https://user-images.githubusercontent.com/109064722/179336897-c9eb3924-e53f-4ed7-88ae-7eb330241786.png)

**Expected behavior**
Numbers should be get from Server not calculated in client, need advise from Tech Lead @loinv22  or CTO @luatnd-lucis 

**To Reproduce**
1. Get an account with more than 5 matches today
2. Go To Dashboard and View All History
3. See error

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
resolved

**Comment by luatnd** [comment]
@Vanntmay plz put the related commit or PR reference here

**Comment by luatnd** [comment]
> resolved

@winwin2211 plz put the commit ref here, eg: "Resolved with commit #210"
