### ISSUE TITLE
[Bug] Lucky Chest - Show different result

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#275]
**Describe the bug (Actual behavior)**
Lucky Chest - Show different result when the arrow is verry close to the right item

Screenshots
https://drive.google.com/drive/u/0/folders/1C4bFrki50VZbJb9zIg7zXMnCVxZx8gcb

https://drive.google.com/file/d/17ASul36QrDje8pYz3fjU2yBLLrof8Wfx/view?usp=sharing

**Expected behavior**
Exactly result

**To Reproduce**
1. Go to 'Lucky Chest'
2. Click on 'Open'
3. Wait for the result arrow is very close to the right item

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chaupa** [comment]
@huyennp 
resolved with commit [34eed05def939c17f0148ee7b332a67e1d3f7775](https://github.com/lucis-network/tournament-app/commit/34eed05def939c17f0148ee7b332a67e1d3f7775)
