### ISSUE TITLE
[Bug] Missing Items in Lucky Chest

### ISSUE THREAD

**Issue by Hwngbob** [lucis-network/tournament-app#287]
**Describe the bug (Actual behavior)**
No Raffle Ticket in Lucky Chest

Screenshots
![image](https://user-images.githubusercontent.com/109072717/179883720-89c93a77-b113-4234-87f0-1ed316a52e11.png)

**Expected behavior**
Base on the Lucky Chest plan, there are Raffle Tickets in LuckyChest.
![image](https://user-images.githubusercontent.com/109072717/179884206-ae14de23-3c08-4834-a40c-cfea5ae8acb1.png)

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by huyennp** [comment]
@tanductan
