### ISSUE TITLE
[Bug] CSGO Don't get new daily missions  on new day

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#300]
**Describe the bug (Actual behavior)**
Yesterday I completed all 4 daily missions, but today I don't get new daily missions. All yesterday mission remains the same

Screenshots
![image](https://user-images.githubusercontent.com/109064722/180365646-f8a67f9f-3b7d-4f56-8feb-5ad82b000611.png)

**Expected behavior**
Should get new daily mission everyday

**To Reproduce**
1. Finish 4 daily mission
2. Go to 'Dashboard'
3. See error

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
fixed with commit https://github.com/lucis-network/tournament-be/commit/14875a38b72b12f52eb50abd84e31f6f720792bf
