### ISSUE TITLE
[Bug] CSGO Wrong mission count "Make 10 kills" and " Play a match with headshots % > 30"

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#316]
**Describe the bug (Actual behavior)**
CSGO Wrong mission count "Make 10 kills" and " Play a match with headshots % > 30"

Screenshots
![image](https://user-images.githubusercontent.com/109064722/181406536-429de657-e202-445b-9bbb-b3137b8a8d1c.png)

**Expected behavior**
"Make 10 Kills" seems counting "Assisst"
"Play a match with headshots % > 30" seems Count Multiple Matches not 1 match

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winwin2211** [comment]
fixed

**Comment by winwin2211** [comment]
resolved with commit https://github.com/lucis-network/tournament-be/commit/e9174eb92eb5ce3715af04a13858017f91276553
