### ISSUE TITLE
[Bug] Raffle show wrong Winner 

### ISSUE THREAD

**Issue by stuart-lucis** [lucis-network/tournament-app#324]
**Describe the bug (Actual behavior)**
When an account, which already won another raffle, visit an ongoing raffle will show that account as a winner.
Other accounts visit raffle won't see this error

Screenshots
![image](https://user-images.githubusercontent.com/109064722/182078772-204666ac-5bd8-4f01-a8ec-d4b0fac39ed1.png)

**Expected behavior**

**To Reproduce**
1. Win Raffle A
2. Go to Raffle B, which is on going
3. See error

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by duccc0926** [comment]
Resolve with commit ea41cda77c3120fbf29f5f1ef748389b5878662b [ea41cda]
