### ISSUE TITLE
[Bug]Ảnh NFT: lệch kính

### ISSUE THREAD

**Issue by luatnd** [lucis-network/tournament-app#326]
**Describe the bug (Actual behavior)**
Bị lệch kính:
nft-preview?character=goat&cloth=monkey&hat=mouse&glasses=goat&weapon=tiger&halo=water&haloLv=6

**Comment by luatnd-lucis** [comment]
Mào gà bị mũ sau chèn lên:
https://play-beta.lucis.network/playcore/nft-preview?character=chicken&cloth=mouse&hat=monkey&glasses=horse&weapon=dog&halo=metal&haloLv=2

**Comment by luatnd** [comment]
Close as fixed 2 days ago
